name: Build

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt update
        sudo apt install -y build-essential libgl1-mesa-dev libxcb-cursor-dev ninja-build

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-2022'
      run: choco install ninja

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.0'
        host: ${{ matrix.os == 'windows-2022' && 'windows' || 'linux' }}
        target: 'desktop'
        arch: ${{ matrix.os == 'windows-2022' && 'win64_msvc2022_64' || 'gcc_64' }}

    - name: Configure MSVC (Windows)
      if: matrix.os == 'windows-2022'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: cmake -S . -B build -G "Ninja Multi-Config" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release -j 4

    - name: Install
      run: cmake --install build --config Release
      shell: bash

    - name: Upload artifacts (Linux)
      if: matrix.os == 'ubuntu-22.04'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-qt6.8.0
        path: |
          ${{ github.workspace }}/build/

    - name: Upload artifacts (Windows)
      if: matrix.os == 'windows-2022'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-qt6.8.0
        path: |
          ${{ github.workspace }}/build/Release/